# Generated by Django 3.0.6 on 2020-06-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='amount',
        ),
    ]
