# Generated by Django 3.0.6 on 2020-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_budget_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
