# Generated by Django 3.0.5 on 2020-06-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('BANK', 'Bank'), ('CRYPTO', 'Crypto')], default='CASH', max_length=50),
        ),
    ]
