# Generated by Django 3.0.5 on 2020-06-01 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_created_date'),
        ('transaction_expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
    ]
