# Generated by Django 3.0.5 on 2020-06-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200601_1226'),
        ('transaction_expense', '0002_transaction_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_expense',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Payment'),
        ),
    ]
