# Generated by Django 3.0.5 on 2020-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_expense', '0004_auto_20200601_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_expense',
            name='family',
        ),
        migrations.AddField(
            model_name='transaction_expense',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
